services:

  notifications_rabbitmq:
    image: rabbitmq:3.13
    networks:
      - project_network
    ports:
      - "5672:5672"

  notifications_pg:
    image: postgres:16
    env_file:
      - postgres.env
    networks:
      - project_network
    volumes:
      - pg_data_notifications:/var/lib/postgresql/data
    ports:
      - "30002:30002"
    command:
      ["postgres", "-c", "log_statement=all"]

  notifications_app:
    build: .
    networks:
      - project_network
    env_file:
      - .env
    ports:
      - "8005:8000"
    command: >
      sh -c "
      /scripts/wait-for-it.sh notifications_rabbitmq:5672 -s -t 60 &&
      /scripts/wait-for-it.sh notifications_pg:30002 -s -t 60 &&
      alembic upgrade head &&
      gunicorn -w 4 -k uvicorn.workers.UvicornWorker web_server:app --bind 0.0.0.0:8000
      "

  notifications_worker:
    build: .
    networks:
      - project_network
    env_file:
      - .env
    command: >
      sh -c "
      /scripts/wait-for-it.sh notifications_rabbitmq:5672 -s -t 60 &&
      /scripts/wait-for-it.sh notifications_pg:30002 -s -t 60 &&
      python worker.py
      "

  notifications_scheduler:
    build: .
    networks:
      - project_network
    env_file:
      - .env
    command: >
      sh -c "
      /scripts/wait-for-it.sh notifications_rabbitmq:5672 -s -t 60 &&
      /scripts/wait-for-it.sh notifications_pg:30002 -s -t 60 &&
      python scheduler.py
      "


  notifications_nginx:
    image: nginx:latest
    networks:
      - project_network
    ports:
      - "85:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./src/core:/etc/nginx/conf.d:ro
    depends_on:
      - notifications_app
    restart: unless-stopped

volumes:
  pg_data_notifications:

networks:
  project_network:
    external: true