services:

  notifications_rabbitmq:
    image: rabbitmq:3.13
    ports:
      - "5672:5672"

  notifications_pg:
    image: postgres:16
    env_file:
      - postgres.env
    networks:
      - project_network
    volumes:
      - pg_data_notifications:/var/lib/postgresql/data
    ports:
      - "30002:30002"
    command:
      ["postgres", "-c", "log_statement=all"]

volumes:
  pg_data_notifications:

networks:
  project_network:
    external: true