[tool.ruff]
line-length = 110

[tool.ruff.lint]
select = ["I", "Q", "E", "ANN", "F"]
ignore = [ "ANN001", "ANN002", "ANN003", "ANN201", "ANN401"]

[tool.mypy]
mypy_path = "src"
exclude = "venv"


[[tool.mypy.overrides]]
module = "kafka.*"
ignore_missing_imports = true


[[tool.mypy.overrides]]
module = "logstash.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "async_fastapi_jwt_auth.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "apscheduler.*"
ignore_missing_imports = true