"""user_id->profile_id

Revision ID: 84cc7f5eab74
Revises: 5e976fa7db4c
Create Date: 2025-04-22 14:15:11.482984

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "84cc7f5eab74"
down_revision: Union[str, None] = "5e976fa7db4c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("notifications", sa.Column("profile_id", sa.Uuid(), nullable=False))
    op.drop_column("notifications", "user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("notifications", sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False))
    op.drop_column("notifications", "profile_id")
    # ### end Alembic commands ###
