"""Notification model init

Revision ID: 5e976fa7db4c
Revises: 05aadc2f2e0b
Create Date: 2025-03-25 17:24:59.978950

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5e976fa7db4c"
down_revision: Union[str, None] = "05aadc2f2e0b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notifications",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("method", sa.Enum("EMAIL", name="notification_method"), nullable=False),
        sa.Column("address", sa.String(), nullable=False),
        sa.Column("subject", sa.String(), nullable=True),
        sa.Column("content", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("notifications")
    # ### end Alembic commands ###
